[plugin]
deps = [{ use = "Reledia/glow", rev = "d8b36ff" }, { use = "Reledia/miller", rev = "40e0265" }, { use = "Reledia/hexyl", rev = "f845ea5" }, { use = "pirafrank/what-size", rev = "f08f7f2" }, { use = "Lil-Dank/lazygit", rev = "c82794f" }]

[flavor]
deps = []
