[[language]]
auto-format = true
language-servers = ["nil", "typos"]
name = "nix"

[language.formatter]
command = "nixpkgs-fmt"

[[language]]
auto-format = true
language-servers = ["godot", "typos"]
name = "gdscript"
[language.formatter]
command = "gdformat"

[[language]]
auto-format = true
language-servers = ["vscode-json-language-server", "typos"]
name = "json"
[language.formatter]
command = "deno"
args = ["fmt", "-", "--ext", "json"]

[language-server]
[language-server.godot]
command = "nc"
args = ["127.0.0.1", "6005"]

[language-server.nil]
command = "nil"

[language-server.typos]
command = "typos-lsp"

[language-server.harper]
command = "harper-ls"
args = ["--stdio"]
